<Login>:
    name: "login"

    email: email
    password: password

    FloatLayout:

        Label:
            text:"Email: "
            font_size: 24
            pos_hint: {"x":0.1, "top":0.9}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: email
            font_size: 24
            multiline: False
            pos_hint: {"x": 0.30 , "top":0.9}
            size_hint: 0.4, 0.07

        Label:
            text:"Password: "
            font_size: 24
            pos_hint: {"x":0.1, "top":0.7}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: password
            font_size: 24
            multiline: False
            password: True
            pos_hint: {"x": 0.30, "top":0.7}
            size_hint: 0.4, 0.07

        Button:
            pos_hint:{"x":0.2,"y":0.05}
            size_hint: 0.3, 0.15
            font_size: 24
            text: "Login"
            on_release:
                root.manager.transition.direction = "up"
                root.loginBtn()


<Main>:
    animal: animal
    raza: raza
    condicion: condicion
    color: color
    datos: datos
    fecha: fecha
    foto: foto

    FloatLayout:

        Label:
            text:"Animal (Gato/Perro): "
            font_size: 24
            pos_hint: {"x":0.1, "top":1}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: animal
            font_size: 24
            multiline: False
            pos_hint: {"x": 0.45 , "top":1}
            size_hint: 0.4, 0.07

        Label:
            text:"Raza: "
            font_size: 24
            pos_hint: {"x":0.1, "top":0.9}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: raza
            font_size: 24
            multiline: False
            pos_hint: {"x": 0.45, "top":0.9}
            size_hint: 0.4, 0.07

        Label:
            text:"Condición (Perdido/encontrado): "
            font_size: 24
            pos_hint: {"x":0.1, "top":0.8}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: condicion
            font_size: 24
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.8}
            size_hint: 0.4, 0.07

        Label:
            text:"Color: "
            font_size: 24
            pos_hint: {"x":0.1, "top":0.7}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: color
            font_size: 24
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.7}
            size_hint: 0.4, 0.07
        
        Label:
            text:"Datos relevantes sobre el animal (edad, nombre, etc.): "
            font_size: 24
            pos_hint: {"x":0.1, "top":0.6}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: datos
            font_size: 24
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.6}
            size_hint: 0.4, 0.07
        
        Label:
            text:"Fecha en la que se perdió/encontró: "
            font_size: 24
            pos_hint: {"x":0.1, "top":0.5}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: fecha
            font_size: 24
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.5}
            size_hint: 0.4, 0.07

        Label:
            text:"Añadir imagen de la mascota: "
            font_size: 24
            pos_hint: {"x":0.1, "top":0.4}
            size_hint: None, None
            size: self.texture_size

        TextInput:
            id: foto
            font_size: 24
            multiline: False
            pos_hint: {"x": 0.45 , "top":0.4}
            size_hint: 0.4, 0.07

        Button:
            pos_hint:{"x":0.2, "y": 0.1}
            size_hint: 0.3, 0.15
            text: "Salir"
            on_release:
                app.root.current = "login"
                root.manager.transition.direction = "down"

